### ISSUE TITLE
Dashboard: Contrast seems to bee a bit weak

### ISSUE THREAD

**Issue by fredewe** [liqd/diid_adplus#13]
**URL:** https://diid-dev.liqd.net/dialoghhu/dashboard/modules/brainstorming-mit-karte/module_basic/
**user:** initiator
**expected behaviour:** 
**behaviour:** Check in left sidebar is difficult to recognise
**important screensize:**
**device & browser:** MacOS 12.1, Latest Safari and Chrome
**Comment/Question:** 
Not sure if the contrast was like that before?
Screenshot?
![Bildschirmfoto 2022-01-27 um 11 16 36](https://user-images.githubusercontent.com/5470479/151339559-08efe2bd-6fcf-458f-b5d9-59d325831b5d.png)

**Comment by fredewe** [comment]
That seems to be the case also on other parts of the platform such as the note-check-thing:
![Bildschirmfoto 2022-01-27 um 11 54 51](https://user-images.githubusercontent.com/5470479/151345460-5ab0a205-8453-4bab-926c-b2d9b141532e.png)

**Comment by fuzzylogic2000** [comment]
But as this is not new, but as the same as before, we will keep it like that and fix later? Or do we need to do that before the release?

**Comment by fredewe** [comment]
We can do that later!
