### ISSUE TITLE
add captcha to registration form

### ISSUE THREAD

**Issue by goapunk** [liqd/diid_adplus#2]
we'll need to add the captcha here as well or only allow hhu logins

**Comment by fuzzylogic2000** [comment]
As we use the DefaultSignupForm, the captcha should already be there after the rebase, when we also add it in the server settings. So, should we just add a task to the rebase story or is there sth. we need to think about or do @fredewe ?

**Comment by fuzzylogic2000** [comment]
@goapunk And that's what you also already did. :)
