### ISSUE TITLE
DIID: Some icons are not shown correctly

### ISSUE THREAD

**Issue by fredewe** [liqd/diid_adplus#20]
**URL:** https://diid-dev.liqd.net/projects/fdsnjakf/?initialSlide=0
**user:** initiator
**expected behaviour:** 
**behaviour:** Icons like arrows in timeline or calendar icon are not shown correctly
**important screensize:**
**device & browser:** MacOS 12.2.1, Safari 15.3, Chrome 99.0.4844.51 
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2022-03-10 um 10 58 03](https://user-images.githubusercontent.com/5470479/157638556-8503ef9c-bc30-40e3-a910-a47049653daf.png)
![Bildschirmfoto 2022-03-10 um 10 48 25](https://user-images.githubusercontent.com/5470479/157638561-95f55708-b726-4da1-a09b-f16df5472832.png)
![Bildschirmfoto 2022-03-10 um 10 47 30](https://user-images.githubusercontent.com/5470479/157638563-3364a6ab-5668-4dcc-8d73-d5964998a809.png)

**Comment by fuzzylogic2000** [comment]
fixed with a+ rebase
