### ISSUE TITLE
DIID Stage: image upload broken

### ISSUE THREAD

**Issue by fredewe** [liqd/diid_adplus#22]
**URL:** https://diid-stage.liqd.net/liqd/dashboard/projects/titel-ihres-projekts/information/
https://diid-stage.liqd.net/liqd/mapideas/2022-00001/
**user:** initiator/user
**expected behaviour:** i can upload images to the server and use them on a+
**behaviour:** the upload does not work and the images are broken
**important screensize:**
**device & browser:** MacOS 12.2.1, Safari 15.3
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2022-03-14 um 13 40 08](https://user-images.githubusercontent.com/5470479/158173939-c11a2190-5739-4e50-a996-68f4a1a19bc2.png)
![Bildschirmfoto 2022-03-14 um 13 41 34](https://user-images.githubusercontent.com/5470479/158174145-c5e050c0-cc86-4f7b-82b8-0ffbf7df63a8.png)
![Bildschirmfoto 2022-03-14 um 13 45 44](https://user-images.githubusercontent.com/5470479/158174884-7c232a7c-1051-4712-86fe-568b13e2f79c.png)

**Comment by fuzzylogic2000** [comment]
fixed in the server settings
