### ISSUE TITLE
saml tests failing

### ISSUE THREAD

**Issue by goapunk** [liqd/diid_adplus#3]
the saml tests are failing and preventing the ci to auto-deploy. Seems to be the case on the old branch in aplus too, so nothing new

**Comment by fuzzylogic2000** [comment]
introduced by [cd1d9ff735065eaba51c30264070ad9d001b8b0b](https://github.com/liqd/diid_adplus/commit/cd1d9ff735065eaba51c30264070ad9d001b8b0b) - the email address has to be verified for the user to log in now.
