### ISSUE TITLE
replace teilhabe with dialog in translations

### ISSUE THREAD

**Issue by goapunk** [liqd/diid_adplus#4]

**Comment by fuzzylogic2000** [comment]
@fredewe I think this is a (small) story.

**Comment by fredewe** [comment]
Do we still need this story?

**Comment by fuzzylogic2000** [comment]
@fredewe No, I currently think, that when we have rebased, this will be just a setting in wagtail. Or maybe we also need to change it either to that setting or the new wording somewhere, but we will just do it, when we get there and include it in the rebase story.
