### ISSUE TITLE
DIID-Register form: Spacing between lines not consistent

### ISSUE THREAD

**Issue by fredewe** [liqd/diid_adplus#63]
**URL:** https://diid-dev.liqd.net/accounts/signup/
**user:** 
**expected behaviour:** The spacing between the lines is the same and the "*" is always in the same line as the last letter.
**behaviour:** See screenshots
**important screensize:**
**device & browser:** MBP 14: MacOS 12.5.1, Safari 15.6.1, Chrome Version 104.0.5112.101, 
iPhone 13: iOS 15.6.1 Safari
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2022-08-29 um 10 23 34](https://user-images.githubusercontent.com/5470479/187158998-d2cbf8d9-a478-46fd-a072-04300a794557.png)

**Comment by fuzzylogic2000** [comment]
Is also an issue in a+ and will be fixed with the next release: https://github.com/liqd/adhocracy-plus/issues/2013
And thus also with the next diid release. Is that early enough?

**Comment by fredewe** [comment]
Thanks, that is early enough.

**Comment by fuzzylogic2000** [comment]
fixed in a+
