### ISSUE TITLE
CKEditor Image Upload is not working

### ISSUE THREAD

**Issue by pascalkienast** [liqd/diid_adplus#87]
**URL:** https://diid-dev.liqd.net
**user:** initator
**expected behaviour:** you should be able to upload images via CKeditor
**behaviour:** there is an error message
**important screensize:** any
**device & browser:** any
**Comment/Question:** it is like this issue on a+ https://github.com/liqd/adhocracy-plus/issues/2570

Screenshot?
<img width="1481" alt="Bildschirmfoto 2024-06-20 um 11 57 55" src="https://github.com/liqd/diid_adplus/assets/6682526/3d57a1c9-ef16-4b1b-b4e7-9a8006e1ba05">

**Comment by goapunk** [comment]
fixed
